name: Build and Test on Linux Mac and Windows

on:
  push:
    branches: [ master ]
    tags: "v*"

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: Test on ${{ matrix.config.os }} with ${{ matrix.config.cc }}
    runs-on: ${{ matrix.config.os }}
    env:
      CC: ${{ matrix.config.cc }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: ubuntu-latest, cc: "gcc", cxx: "g++"}
        - {os: ubuntu-latest, cc: "clang", cxx: "clang++"}
        - {os: macos-latest, cc: "clang", cxx: "clang++"}
        - {os: windows-latest, cc: "cl", cxx: "cl"}

    steps:
      - uses: actions/checkout@v2

      - if: matrix.os != 'windows-latest'
        name: Install TBB
        run: sudo apt install libtbb-dev

      - name: Info
        run: echo ${{ github.ref }}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
